# Google Cloud Build 配置文件
# 用于构建和部署 MyShell 2025 开发者年度回顾项目

steps:
  # 步骤 1: 使用 Docker 构建镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/myshell-recap:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/myshell-recap:latest',
      '.'
    ]
    id: 'build-image'

  # 步骤 2: 推送镜像到 Container Registry（可选）
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/myshell-recap:$COMMIT_SHA']
  #   id: 'push-image'
  #   waitFor: ['build-image']

# 超时时间（顶层配置）
timeout: '1800s'  # 30 分钟

# 构建选项
options:
  # 使用 CLOUD_LOGGING_ONLY 来解决 service_account 配置问题
  logging: CLOUD_LOGGING_ONLY

  # 机器类型（可选，根据项目大小调整）
  machineType: 'N1_HIGHCPU_8'

# 构建产物（可选）
# artifacts:
#   objects:
#     location: 'gs://your-bucket-name/build-artifacts'
#     paths: ['dist/**']
